clux/muslrust

.gitignore, Makefile
This adds an extra (non-phony) target `.build` to flag if a docker image
has already been built.
=> Tests can now depend on the `build` target.

Dockerfile
This is a build argument that you can pass in the `docker build`
command. With this you can pin the Rust nightly version to a snapshot (i.e.
`--build-arg NIGHTLY_SNAPSHOT=2017-06-13` for rust-nightly-2017-06-13).
The default behavior is unaffected, it will build with the latest like normal.
=> Add NIGHTLY_SNAPSHOT build arg

Dockerfile, Makefile, README.md, test.sh, test/pqcrate/Cargo.toml, test/pqcrate/src/main.rs
before setting the PQ_LIB_STATIC, we would still try to dynamically link with libpq, now it at least tries, but the test crate fails with a link error. It's a start.
=> attemps at libpq - resumed from #17

Makefile, README.md
Basically to allow continued building despite #32 
Maybe there's a better solution, but would rather keep producing perfectly valid nighties with at least the guarantee that the normal stable modules work on them for now. Can always re-add rocket back if it becomes more stable.
=> Unblock rocket + docs tweaks

Dockerfile, update_libs.py
This implements #38, pulling the latest version of packages from Arch repos using their API and updating Dockerfile as needed using a fairly short and simple Python script with comments and tests.
Two packages have their versions modified from the original `pkgver`:
- `openssl-1.0`: Arch's packages add a period between the final digit and the letter in the version.
- `sqlite`: Download URLs for SQLite use a zero-padded string of numbers with no periods.
A second commit was added after running said script, updating the libraries.
=> Update libraries automatically from Arch Linux repos

Dockerfile
Solves:
"Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed."
=> Don't rely on CircleCI's native git

Dockerfile
[Rustup 1.12.0] introduced profiles and changed the default installation to include more components. Now, rustfmt and clippy are included by default in the "default" profile. A new "minimal" profile is also
available and should be used in CI from now on. Compared to the previous default install, it is lighter as it does not include rust-docs.
The difference in default components can be seen in recent CI runs, one before and one after the new rustup release:
2019-10-11: https://travis-ci.org/clux/muslrust/builds/596639602#L797-L800
2019-10-15: https://travis-ci.org/clux/muslrust/builds/598191165#L798-L803
[Rustup 1.12.0]: https://blog.rust-lang.org/2019/10/15/Rustup-1.20.0.html
=> Install the minimal rustup profile

README.md
Since Rustup has been added to the image, Clippy can be installed via Rustup instead of compiling via `cargo install`. The "Clippy" section has been renamed to "Binaries distributed via Cargo" and the example of Clippy has been changed out with Ripgrep.
A new section has been added called "Extra Rustup components" which just notes that extra Rustup components like Clippy can be installed like normal.
=> Update documentation on Clippy and installing extra components/binaries

.travis.yml
Similar to #14, but for perhaps different reasons.
Using an unpinned nightly means that when this docker container is used to build another one (adding in special libraries and tools for a project's build container), it may fail when using rustup to download a component. Even if the component is available for the nightly that the docker container was built with, it will fail because it is looking for "nightly"'s version of the component instead of "nightly-XXX-XX-XX"'s version.
Example: Right now (2019-10-16) clippy is missing in nightly, but was there yesterday:
https://rust-lang.github.io/rustup-components-history/index.html
If the container for `nightly-2019-10-15` is used, it will fail to download clippy even though it exists for the nightly the container was built with.
```
$ docker …
```
=> Pin nightly to a date instead of using "nightly" as the toolchain

Dockerfile
seems to pass ssl tests (`make build && make test-ssl`)
have pushed `clux/muslrust:1.55.0-openssl11` with this build currently. if anyone is able to test it out a bit more that would be great.
=> Try to upgrade openssl the naive way

Dockerfile
After the recent update to jammy, `apt-get install` has started prompting an interactive while trying to configure tzdata.
```
Please select the geographic area in which you live. Subsequent configuration questions will narrow this down by presenting a list of cities, representing the time zones in which they are located.
1. Africa  2. America  3. Antarctica  4. Australia  5. Arctic  6. Asia  7. Atlantic  8. Europe  9. Indian  10. Pacific  11. US  12. Etc
```
This silences the prompt and sets the timezone to UTC by default
**Steps to reproduce:**
1. docker run -it clux/muslrust
2. apt-get update && apt-get install -y awscli
=> silence tzdata

Dockerfile, etc/profile.d/cargo.sh
This makes building as `root` and as a non-root user behave the same.
Before, building as a non-root user (i.e., via `podman run --userns=keep-id`) would be different in the following ways:
- It would not automatically source `/etc/profile.d/cargo.sh` (at least for me)
- As a result, `RUSTUP_HOME` would not be set and cargo would complain about not having a default target
- It would not build against the `x86_64-unknown-linux-musl` target because [cargo's default config location is `~/.cargo/config`](https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure), but we only write our desired build target into `~root/.cargo/config`, which is not checked when a non-root user invokes cargo
This PR fixes all that by configuring all those settings as environment variables …
=> fix: Unify `root` and non-root user behavior

Dockerfile
tonic-build require protoc cli tool to generate the codes, install
protobuf-compiler allow user can use this image to build tonic codes
directly
Signed-off-by: Sherlock Holo <sherlockya@gmail.com>
=> feat: install protobuf-compiler to add protoc

Dockerfile
To build rdkafka with musl `cmake` must be installed.
closes https://github.com/clux/muslrust/issues/109
=> chore: add cmake to support rdkafka

Dockerfile
Hi, would you take a PR to uprev protobuf?
This gets to 1.25, from 1.12 which is 4 years old
Thanks for your work
=> install protobuf compiler from releases instead of apt

.github/workflows/nightly.yml, .github/workflows/stable.yml
I noticed `stable` got released to docker again today and upon further investigation it looks like [this](https://github.com/clux/muslrust/blob/main/check_stable.py#L41) tag was missing.
=> add missing tags

README.md, test/serdecrate/Cargo.toml, test/serdecrate/src/main.rs
references #142 and does it in one example
=> Add hints about changing allocators

README.md, SCCACHE.md
as requested (https://github.com/clux/muslrust/pull/144#pullrequestreview-2072561465), here's some docu about using sccache
let me know if this looks okay to you. thanks
=> add some documentation about using sccache with this image

.github/workflows/nightly.yml, .github/workflows/stable.yml, Dockerfile.arm64, Dockerfile.test-runner, Dockerfile.x86_64, README.md, justfile
red CI on arm with compiler errors and core dumps for 3 weeks. resolved by:
- updating ubuntu (sidesteps issue)
- remving curl #96
- updating deps (nothing major)
The only big change here should curl removal, which at this point SHOULD be reasonable. I doubt many people use curl crate over hyper at this point, and if you are, you probably shouldn't. Anyway, reach out on #96 if you disagree.
=> Update ubuntu for arm compiler crashes

Dockerfile.arm64, test/rustlscrate/Cargo.toml, test/rustlscrate/src/main.rs
To see if we can build rustls deps with aws-lc
closes #141 
Updating tests is enough. Example taken from [hyper-rustls](https://docs.rs/hyper-rustls/latest/hyper_rustls/)
It works out of the box because the `aws-lc-sys` crate just works and passes tests provided i actually update rustls in the test suite.
pointless log of my exploration of actually compiling it.
<details><summary>building it from docker</summary>
<p>
avoided by not doing any linking in the build (turning off tool, libssl build and test builds)
for posterity the following invocation does at least compile in the image
```dockerfile
RUN curl -sSL https://github.com/aws/aws-lc/archive/refs/tags/v${AWS_LC_VER}.tar.gz | tar xz && \
mkdir aws-lc-build && cd aws-lc-build && \
cmake -GNinja \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \ …
```
=> aws-lc tests

.github/workflows/nightly.yml, .github/workflows/stable.yml
closes https://github.com/clux/muslrust/pull/148
should give a new build summary in the action. EDIT: [yes](https://github.com/clux/muslrust/actions/runs/15163358357/attempts/1#summary-42634661189)
=> Bump docker/build-push-action from 5 to 6

Dockerfile
This PR updates the `Dockerfile` to use [HereDoc syntax](https://docs.docker.com/reference/dockerfile/#here-documents), as suggested [here](https://github.com/clux/muslrust/issues/139#issuecomment-2833954251). This allows for `RUN` statements to drop the `&& \` noise and be easier to grok like a regular shell script.
If you review the first commit that should be fairly straight-forward. I've since noticed other portions of the `Dockerfile` that could do with some maintenance, but lack time to stagger PRs for each individually, the bulk of those are in the follow-up commits (_might be easier to review separately if you rely on a diff_).
---
**Additionally:**
- `ENV CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse` can be dropped as this is the [default since Rust …
=> chore: `Dockerfile` use HereDoc syntax

Dockerfile
The `awk` approach looked...awkward 🥁 This is more DRY 😎
This pipes the value into `xargs` that splits the `SQLITE_VERSION` string by `.` as the delimiter and passes those as args to `printf` command which is formatting the `major.minor.patch` values similar to how the original Python script did (_or your individual `printf` formats with each one parsed via `awk`_).
=> chore: `Dockerfile` - Simplify formatting `SQL_ID`

.github/workflows/stable.yml
For the most part this just pulls the stable check script to the start of the workflow to bail early instead of littering the same conditional in many steps that follow (including build and tests).
The other big change is the final step to assign more tags to the image when it is published. The logic should be the same, I've just rearranged it to be a bit nicer to grok.
**NOTE:** Given that you've centralized to a single `Dockerfile` now, and it can be built successfully with multiple platforms (without a build arg for the arch necessary), you could avoid all this dance with the tag management.
- Only the extraction of the `RUST_VER` is a little tricky, but you should be able to just append that tag in a post publish step?
- You've also got the option to use the ARM64 runner for `aarch64` …
=> ci: Refactor `stable.yml`

test.sh
I intended this to be a bit smaller but figured I might as well tidy up the whole file while I'm at it.
---
Despite the large diff, it should function effectively the same, except `docker_build` now uses `ldd` in the container instead of `file`, like the other tests as the QEMU bug has been resolved since Aug 2023 (QEMU 8.1.0).
I normalized some of the script for consistency:
- The other two "helper" methods seemed dated and only intended for troubleshooting reference during development? I split out the common verification portion to a separate function call `check_crate_build_locally()`.
- The read-only state `-r` assigned to the `crate` var (now `CRATE_NAME`) seemed unnecessary. The variable was hoisted out of the functions, thus they can't be prefixed `local` (_given it's a small …
=> chore: Refactor `test.sh`
